export const DATA = [
  {
    title: "Ford Fiesta",
    category: "Economy Car",
    image: "https://ibb.co/Myb38yYF",

    description: "This is the description for News Title 2.",
    date: "2023-03-22T15:59:07.338Z",
    author: "Emily Williams",
    isOfficial: true,
  },
  {
    title: "Nissan Versa",
    category: "Compact Car",
    image: "https://picsum.photos/id/219/500/300",
    description: "This is the description for News Title 24.",
    date: "2023-04-28T18:57:33.699Z",
    author: "Robert Brown",
    isOfficial: true,
  },
  {
    title: "Toyota Corolla",
    category: "Mid-size Car",
    image: "https://picsum.photos/id/918/500/300",
    description: "This is the description for News Title 82.",
    date: "2023-04-22T04:03:54.560Z",
    author: "Emily Williams",
    isOfficial: false,
  },
  {
    title: "Nissan Rogue",
    category: "Mid-size SUV",
    image: "https://picsum.photos/id/1073/500/300",
    description: "This is the description for News Title 42.",
    date: "2023-07-14T01:15:37.707Z",
    author: "Emily Williams",
    isOfficial: true,
  },
  {
    title: "Chevy Traverse",
    category: "Full-size SUV ",
    image: "https://picsum.photos/id/456/500/300",
    description: "This is the description for News Title 69.",
    date: "2023-01-21T23:25:33.906Z",
    author: "Michael Johnson",
    isOfficial: false,
  },
  {
    title: "Nissan Altima",
    image: "https://picsum.photos/id/189/500/300",
    category: "Full-size Car",
    description: "This is the description for News Title 97.",
    date: "2023-02-02T05:36:24.228Z",
    author: "John Doe",
    isOfficial: false,
  },
];
