

export const DATA = [
  {
    title: "Ford Fiesta",
    category: "Economy Car",
    image: "/src/assets/img/car1.png",
    user: "5 Seats",
    scors: "Automatic",
    date: "21+ Years",
    valume: "1-lit / 2.5 km",
  },
  {
    title: "Nissan Versa",
    category: "Compact Car",
    image: "/src/assets/img/car2.png",
    user: "5 Seats",
    scors: "Automatic",
    date: "21+ Years",
    valume: "1-lit / 2.5 km",
  },
  {
    title: "Toyota Corolla",
    category: "Mid-size Car",
    image: "/src/assets/img/car3.png",
    user: "5 Seats",
    scors: "Automatic",
    date: "21+ Years",
    valume: "1-lit / 2.5 km",
  },
  {
    title: "Nissan Rogue",
    category: "Mid-size SUV",
    image: "/src/assets/img/car4.png",
    user: "5 Seats",
    scors: "Automatic",
    date: "21+ Years",
    valume: "1-lit / 2.5 km",
  },
  {
    title: "Chevy Traverse",
    category: "Full-size SUV ",
    image: "/src/assets/img/car5.png",
    user: "5 Seats",
    scors: "Automatic",
    date: "21+ Years",
    valume: "1-lit / 2.5 km",
  },
  {
    title: "Nissan Altima",
    image: "/src/assets/img/car6.png",
    category: "Full-size Car",
    user: "5 Seats",
    scors: "Automatic",
    date: "21+ Years",
    valume: "1-lit / 2.5 km",
  },
];
